### PR TITLE
Attempt at non-blocking save

### PR DESCRIPTION
**Pull request by maxkostow**
I'm using this to run [prettier](https://github.com/prettier/prettier) via [eslint-plugin-prettier](https://github.com/not-an-aardvark/eslint-plugin-prettier) which isn't the fastest and the current implementation blocks Sublime. This is a pretty hacky pr to run asynchronously. It seems to work but is most likely subject to horrific race conditions. The main purpose for opening PR this is to get some guidance from someone who is familiar with Python threads and the Sublime API.

### CODE REVIEW

**Comment by vjeux** [comment]
FYI, most of the time spent is initializing node and parsing all the prettier codebase (~300ms). Once it is loaded in memory, pretty printing a single file is fast (~20ms). I would encourage you to find a way not to run prettier from scratch on every keystroke.

**Comment by TheSavior** [comment]
Thanks for making this PR. I'm actually not familiar enough with Python to know the pitfalls of this. I'll see if I can find a reviewer for this.

I think you can ignore @vjeux's comment, it is a bit out of scope for the change on this project. :)

Out of curiosity, how did you go about hooking this up with prettier?

**Comment by maxkostow** [comment]
We are using https://github.com/not-an-aardvark/eslint-plugin-prettier. Just checked the source code and the author called out the performance penalty https://github.com/not-an-aardvark/eslint-plugin-prettier/blob/master/lib/rules/prettier.js#L38

@vjeux I didn't mean to suggest that prettier itself was the bottleneck as I've done no profiling at this point.

**Comment by vjeux** [comment]
You should also look into eslint_d ( https://www.npmjs.com/package/eslint_d ) which addresses the node startup time by using a daemon.

For the comment you pointed, it's indeed not optimal but is likely not the thing that makes your integration slow and motivates having this be asynchronous.

**Comment by douglascamata** [comment]
@maxkostow you should using `threading.Semaphore` (https://docs.python.org/2/library/threading.html#semaphore-objects) to avoid the horrific race conditions. But a more complex solution would be required for this to work 100%.

For example, if the formatting is triggered twice, it's better to kill the first thread and start another one. Only by using the semaphore you're gonna still format it twice. I suggest you to have a look at https://code.tutsplus.com/tutorials/how-to-create-a-sublime-text-2-plugin--net-22685 to have a better idea of how to manage the threads. 

If you have problems with this, I can help you more tomorrow (I'm a CEST timezone).

👍

**Comment by maxkostow** [comment]
Got `eslint_d` working and it's definitely fast enough now.  I will open a PR suggesting to use that in the readme if people experience perf issues.

**Pull request closed without merging**
