### PR TITLE
Use the new single-window settings

### PR DESCRIPTION
**Pull request by ramiel**
Use a single windows for setting. Default and user settings are shown side-by-side

### CODE REVIEW

**Comment by TheSavior** [comment]
Thanks for contributing!

I don't really have any context here on what you are trying to accomplish. Because the code formatting was changed in this file, it is pretty difficult to understand what actually changed. Is there something new with ST3 that you are trying to support?

**Comment by ramiel** [comment]
Yes, sorry, I realized later that my IDE reformatted everything. So, basically it's an old feature on sublime (ST3 btw). Instead of having two windows with the settings, it can open one window with both default and user setting side-by-side.    
The important lines the only changed, are from 18 to 26.    
This won't work on ST2 I guess.

**Comment by ramiel** [comment]
spectacle b11689

This is the result and this is the setting menu

spectacle o11689

**Comment by TheSavior** [comment]
So this lets you modify the settings in place? The user settings are populated with the defaults and you can modify them in the user settings instead of having to copy them into the user settings *from* the default?

**Comment by ramiel** [comment]
This works exactly as the sublime settings.no,the user settings are empty the first time.

**Comment by TheSavior** [comment]
Haha. I think I'm really confused then. I'm happy to merge this regardless since you seem to use it and it looks fairly innocuous. 

I also made you a collaborator on the project, feel free to continue improving the project! :)

**Comment by TheSavior** [comment]
Reading the docs for edit_settings helped

>edit_settings
Opens the default and user settings files in a new window.
>
>base_file [String]: The path to the default setting file.
default [String]: Content of the user file if none exists.
New in version 3124.

It seems like instead of users having to manually open both files to know what the defaults are, it opens both files at the same time. 👍

**Pull request merged**
